version: "3"

services:
  database:
    container_name: database
    build:
      context: data
    env_file: ./.devops/data/.env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
  
  wordpress:
    container_name: wordpress
    depends_on:
      - database
    image: wordpress:latest
    env_file: ./.devops/wordpress/.env
    volumes:
      - wp-content:/var/www/html/wp-content
    restart: always
    ports:
      - 8080:80
      - 443:443

volumes:
  database:
    driver: local